[versions]
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"

webClient = "1.7.2"
kmpDateTime = "2.2.1"
klf = "1.8.3"

jackson = "2.21.0"

# test
logback = "1.5.26"

assertk = "0.28.1"


[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

webClientApi = { module = "net.dankito.web:web-client-api", version.ref = "webClient" }
ktorWebClient = { module = "net.dankito.web:ktor-web-client", version.ref = "webClient" }
kmpDateTime = { module = "net.dankito.datetime:kmp-datetime", version.ref = "kmpDateTime" }
klf = { module = "net.codinux.log:klf", version.ref = "klf" }

jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-dateTime = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }

# test
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }


[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }